# pylint: skip-file
# Generated by Django 4.2.23 on 2025-07-06 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('sort_name', models.CharField(max_length=4096)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=1048576, null=True)),
                ('phone_number', models.CharField(max_length=4096)),
                ('email', models.CharField(max_length=4096)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('description', models.TextField(blank=True, max_length=1048576, null=True)),
                ('contact_information', models.TextField(blank=True, max_length=1048576, null=True)),
                ('principle_investigators', models.TextField(blank=True, max_length=1048576, null=True)),
                ('participants_target', models.IntegerField(blank=True, null=True)),
                ('recruitment_starts', models.DateField(blank=True, null=True)),
                ('recruitment_ends', models.DateField(blank=True, null=True)),
                ('study_starts', models.DateField(blank=True, null=True)),
                ('study_ends', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('staff_members', models.ManyToManyField(related_name='research_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted', models.DateField(blank=True, null=True)),
                ('enrolled', models.DateField(blank=True, null=True)),
                ('exited', models.DateField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=4096, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='simple_research.researchparticipant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='simple_research.researchstudy')),
            ],
        ),
    ]
