# pylint: skip-file
# Generated by Django 5.2.5 on 2025-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchparticipant',
            name='email',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='researchparticipant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='researchparticipant',
            name='sort_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
