# pylint: skip-file
# Generated by Django 5.2.14 on 2026-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_research', '0002_alter_researchparticipant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstudy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
