# pylint: skip-file
# Generated by Django 3.2.25 on 2026-07-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_research', '0003_researchstudy_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchParticipantVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('name', models.CharField(max_length=4096)),
                ('sort_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=1048576, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=4096, null=True)),
                ('email', models.CharField(blank=True, max_length=4096, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='simple_research.researchparticipant')),
            ],
        ),
    ]
