# pylint: skip-file
# Generated by Django 3.2.25 on 2026-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_research', '0004_researchparticipantversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchparticipant',
            name='known_phone_numbers',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
    ]
